- .github/CONTRIBUTING.md
This PR updates the branch name reference in the contributing guidelines.
Initially, the contributing guidelines were written assuming the default branch was `main`. Now, the default branch is `develop`. This change ensures that contributors start from the correct `develop` branch.
If this PR is accepted and merged, it would be worthwhile to double-check the repository to ensure no other unintended references to `main` remain.
> docs: update branch name reference in contributing guidelines

- CHANGELOG.md
- OUDS/Core/Themes/Sources/Shared/OUDSTheme+SemanticTokens/OUDSTheme+OpacitySemanticTokens.swift
- OUDS/Core/Themes/Tests/Shared/ThemeOverrideOfOpacitySemanticTokens.swift
- OUDS/Core/Themes/Tests/Shared/_/MockTheme+OpacitySemanticTokens.swift
- OUDS/Core/Tokens/RawTokens/Tests/OpacityRawTokensTests.swift
- OUDS/Core/Tokens/SemanticTokens/Sources/OpacitySemanticTokens.swift
THis commit updates when needed the values of raw tokens and semenatic tokens for opacity. It brings also unit tests for theme overriding and raw tokens relationships.
#29
Update raw and semantic tokens for opacity
See #29
- (NA) The evolution have been tested and the project builds for iPhones and iPads
- (NA) Internal files have been updated if relevant (like CONTRIBUTING, DEVELOP, …
> [#29] Add raw tokens and semantic tokens for opacity 

- CHANGELOG.md
- OUDS/Core/Themes/Sources/Shared/OUDSTheme+SemanticTokens/OUDSTheme+TypographySemanticTokens.swift
- OUDS/Core/Themes/Tests/Shared/ThemeOverrideOfTypographySemanticTokens.swift
- OUDS/Core/Themes/Tests/Shared/_/MockTheme+TypographySemanticTokens.swift
- OUDS/Core/Tokens/RawTokens/Sources/TypographyRawTokens.swift
- OUDS/Core/Tokens/RawTokens/Tests/TypographyRawTokensTests.swift
- OUDS/Core/Tokens/SemanticTokens/Sources/TypographySemanticTokens.swift
> [#51] Add raw and semantic tokens for typography

- CHANGELOG.md
- Showcase/Showcase.xcodeproj/project.pbxproj
This version 0.0.0 must be seens as a canary version of the OUDS iOS library with several aims:
- prepare the code base for the documentation work with DocC
- test the CI/CD pipeline for the whole process (with both beta and production builds)
- avoid to have stale branches with tokens taking long time to be merged
- review th delivery process
- test the architecture of the library
> Prepare release 0.0.0

- OUDS/Core/Tokens/RawTokens/Sources/OpacityRawTokens.swift
Closes #87 
This PR updates the value of `opacity800` from `0.88` to `0.80` following the modification in Figma tokens.
- (N/A) My change follows accessibility good practices
- (N/A) My change introduces changes to the documentation and/or I have updated the documentation accordingly
- (N/A) Design review has been done
- (N/A) Accessibiltiy review has been done
- (N/A) Q/A team has tested the evolution
> feat(opacity): update `opacity800` from `0.88` to `0.80`

- .github/DEVELOP.md
- CHANGELOG.md
- OUDS/Core/Components/Sources/Forms/TextInput/OUDSFormsTextInput.swift
- OUDS/Core/Tokens/RawTokens/Sources/BorderRawTokens.swift
- OUDS/Core/Tokens/RawTokens/Sources/ElevationRawTokens.swift
- OUDS/Core/Tokens/SemanticTokens/Sources/BorderSemanticTokens.swift
- OUDS/README.md
#89
- @julien-deramond spotted some typo in documentation
- I create the issue #89 for his evolution and a dedicated branch to update CHANGELOG and fix more typos
See #89
- (N/A) My change follows accessibility good practices
- (N/A) My change respects the design guidelines of _Orange Unified Design System_
- (N/A)  I have added unit tests to cover my changes _(optional)_
- (N/A) Design review has been done
- (N/A) Accessibiltiy review has been done
- (N/A) Q/A team has tested the evolution
> [#89] Fixes some typo in documentation

- CHANGELOG.md
- OUDS/Core/Tokens/RawTokens/Sources/OpacityRawTokens.swift
- OUDS/Core/Tokens/RawTokens/Tests/OpacityRawTokensTests.swift
#87
- @julien-deramond submtited a PR to update _opacity800_ (#86)
- I checked his branch
- I merge into another branch so as to update the CHANGELOG and add a missing unit tests
See #87 
- (N/A) My change follows accessibility good practices
- (N/A)  My change respects the design guidelines of _Orange Unified Design System_
- (N/A) Design review has been done
- (N/A) Accessibiltiy review has been done
- (N/A) Q/A team has tested the evolution
> [#87] Update value for opacity800

- CHANGELOG.md
- OUDS/Core/OUDS/Sources/OUDSTheme/OUDSTheme+SemanticTokens/OUDSTheme+BorderSemanticTokens.swift
- OUDS/Core/OUDS/Tests/OUDSTheme/MockTheme/MockTheme+BorderSemanticTokens.swift
- OUDS/Core/OUDS/Tests/OUDSTheme/TestThemeOverrideOfBorderSemanticTokens.swift
- OUDS/Core/Tokens/RawTokens/Sources/BorderRawTokens.swift
- OUDS/Core/Tokens/RawTokens/Tests/BorderRawTokensTests.swift
- OUDS/Core/Tokens/SemanticTokens/Sources/BorderSemanticTokens.swift
#58
- Rmeove useless border raw tokens for radius circle and radius pill
Be compliant with specifications
- Breaking change (fix or feature that would change existing functionality)
> [#58] Remove border tokens radius circle and radius pill (#58)

- CHANGELOG.md
- OUDS/Core/OUDS/Sources/OUDSTheme/OUDSTheme+SemanticTokens/OUDSTheme+SizingSemanticTokens.swift
- OUDS/Core/OUDS/Sources/OUDSTheme/OUDSTheme+SemanticTokens/OUDSTheme+SpacingSemanticTokens.swift
- OUDS/Core/OUDS/Tests/OUDSTheme/MockTheme/MockTheme+SizingSemanticTokens.swift
- OUDS/Core/OUDS/Tests/OUDSTheme/MockTheme/MockTheme+SpacingSemanticTokens.swift
- OUDS/Core/OUDS/Tests/OUDSTheme/TestThemeOverrideOfSizingSemanticTokens.swift
- OUDS/Core/OUDS/Tests/OUDSTheme/TestThemeOverrideOfSpacingSemanticTokens.swift
- OUDS/Core/Tokens/SemanticTokens/Sources/SizingSemanticTokens.swift
- OUDS/Core/Tokens/SemanticTokens/Sources/SpacingSemanticTokens.swift
#36 (but should not be closed)
- Manage viewports for regular and compact modes fir sizing and spacing tokens
- Add more tests
> [#36] Manage regular and compact layouts for sizing and spacing tokens

- CHANGELOG.md
- OUDS/Core/Components/Sources/_OUDSComponents.docc/_OUDSComponents.md
- OUDS/Core/OUDS/Sources/OUDSTheme/OUDSTheme+SemanticTokens/OUDSTheme+ElevationSemanticTokens.swift
- OUDS/Core/OUDS/Tests/OUDSTheme/MockTheme/MockTheme+ElevationSemanticTokens.swift
- OUDS/Core/OUDS/Tests/OUDSTheme/TestThemeOverrideOfElevationSemanticTokens.swift
- OUDS/Core/Themes/Inverse/Sources/InverseTheme+ElevationSemanticTokens.swift
- OUDS/Core/Tokens/RawTokens/Sources/ElevationRawTokens.swift
- OUDS/Core/Tokens/RawTokens/Tests/ElevationRawTokensTests.swift
- OUDS/Core/Tokens/SemanticTokens/Sources/ElevationSemanticTokens.swift
- Showcase/Showcase.xcodeproj/project.pbxproj
- Showcase/Showcase/Pages/Components/ComponentsPage.swift
- Showcase/Showcase/Pages/Components/Elevations/ElevationsList.swift
#32
Shadow effect of elevation can be computed only with Figma blur, thus the spread is useless.
Remove spread properties, update tests, add some fake components in demo app for visual tests, update doc.
Closes #32
- Breaking change (fix or feature that would change existing functionality)
> Remove spread value from elevation tokens

- CHANGELOG.md
- OUDS/Core/Components/Sources/Buttons/OUDSButton.swift
- OUDS/Core/Components/Sources/Extensions/View+Font.swift
- OUDS/Core/Components/Sources/Forms/TextInput/OUDSFormsTextInput.swift
- OUDS/Core/Components/Sources/ViewModifiers/BorderStyleModifier.swift
- OUDS/Core/Components/Sources/ViewModifiers/CustomFontModifier.swift
- OUDS/Core/Components/Sources/ViewModifiers/FontModifier.swift
- OUDS/Core/OUDS/Sources/OUDSTheme/OUDSTheme+ComponentTokens/OUDSTheme+ButtonsComponentTokens.swift
- OUDS/Core/OUDS/Sources/OUDSTheme/OUDSTheme+ComponentTokens/OUDSTheme+FormsTextInputComponentToken.swift
- OUDS/Core/OUDS/Sources/_OUDS.docc/Themes.md
- OUDS/Core/OUDS/Sources/_OUDS.docc/Tokens.md
- OUDS/Core/Tokens/ComponentTokens/Sources/ButtonsComponentTokens.swift
- OUDS/Core/Tokens/ComponentTokens/Sources/FormsTextInputComponentTokens.swift
- OUDS/Core/Tokens/ComponentTokens/Sources/_OUDSTokensComponent.docc/OUDSTokensComponent.md
- OUDS/Foundations/Sources/Extensions/String+SwiftUI.swift
- OUDS/README.md
- Showcase/Showcase/OrangeCustomTheme.swift
- Showcase/Showcase/Pages/Guidelines/GuidelinesPage.swift
No issue
Add a fake `OUDSButton` with its component tokens so as to test typgoraphy, border and some view modifiers.
Improve also the public and internal API for view drawings.
Have something more and new for demo, and go a bit further with components because of the lack of specifications!
None
> Add some fake components and tokens for demo and tests

- CHANGELOG.md
- OUDS/Core/OUDS/Sources/OUDSTheme/OUDSTheme+SemanticTokens/OUDSTheme+BorderSemanticTokens.swift
- OUDS/Core/OUDS/Sources/_OUDS.docc/Themes.md
- OUDS/Core/OUDS/Tests/OUDSTheme/MockTheme/MockTheme+BorderSemanticTokens.swift
- OUDS/Core/OUDS/Tests/OUDSTheme/TestThemeOverrideOfBorderSemanticTokens.swift
- OUDS/Core/Tokens/SemanticTokens/Sources/BorderSemanticTokens.swift
- OUDS/README.md
- Showcase/Showcase/OrangeCustomTheme.swift
#106
Apply new values for border semantic tokens
> Update border semantic tokens (#106)

- CHANGELOG.md
- OUDS/Core/Tokens/RawTokens/Sources/Values/ElevationRawTokens+Values.swift
- OUDS/Core/Tokens/RawTokens/Tests/ElevationRawTokensTests.swift
- OUDS/Core/Tokens/SemanticTokens/Sources/TypeAliases/ElevationSemanticTokens+Aliases.swift
Closes #119
#119 
- Add missing raw toekn elevation X 200
- Remove Z Index raw tokens for elevations
> [#119] Remove tokens `elevationZIndex` and add `elevationX200`

- CHANGELOG.md
- OUDS/Core/Tokens/RawTokens/Sources/Composites/TypographyRawTokens+Composites.swift
- OUDS/Core/Tokens/RawTokens/Sources/TypeAliases/TypographyRawTokens+Aliases.swift
- OUDS/Core/Tokens/RawTokens/Sources/Values/TypographyRawTokens+Values.swift
- OUDS/Core/Tokens/RawTokens/Tests/TypographyRawTokensTests.swift
#51
Add last tokens and unit tests
-(NA) My change follows accessibility good practices
-(NA) My change respects the design guidelines of _Orange Unified Design System_
-(NA) Design review has been done
-(NA) Accessibiltiy review has been done
-(NA) Q/A team has tested the evolution
> [#51] Update typography tokens

- CHANGELOG.md
- OUDS/Core/OUDS/Sources/_OUDS.docc/Tokens.md
- OUDS/Core/Tokens/RawTokens/Sources/_OUDSTokensRaw.docc/OUDSTokensRaw.md
- OUDS/Core/Tokens/SemanticTokens/Sources/_OUDSTokensSemantic.docc/OUDSTokensSemantic.md
- OUDS/README.md
#127
Add more details about how to define, add, update or remove raw and semantic tokens
> [#127] Add more details about raw and semantic tokens definitions in documentation

- CHANGELOG.md
- OUDS/Core/OUDS/Sources/OUDSTheme/OUDSTheme+SemanticTokens/OUDSTheme+GridSemanticTokens.swift
- OUDS/Core/OUDS/Tests/OUDSTheme/MockTheme/MockTheme+GridSemanticTokens.swift
- OUDS/Core/OUDS/Tests/OUDSTheme/TestThemeOverrideOfGridSemanticTokens.swift
- OUDS/Core/Tokens/RawTokens/Sources/Values/GridRawTokens+Values.swift
- OUDS/Core/Tokens/RawTokens/Tests/GridRawTokensTests.swift
- OUDS/Core/Tokens/SemanticTokens/Sources/TypeAliases/GridSemanticTokens+Aliases.swift
- OUDS/Core/Tokens/SemanticTokens/Sources/Values/GridSemanticTokens.swift
#139 
Remove useless tokens
Keep the stack updated and aligned with *Figma*
- Breaking change (fix or feature that would change existing functionality)
> [#139] Remove web-specific grid raw tokens and non-max-min-width grid semantic tokens

- CHANGELOG.md
- OUDS/Core/Components/Sources/ViewModifiers/BorderModifiers/BorderModifier.swift
- Showcase/Showcase.xcodeproj/project.pbxproj
- Showcase/Showcase/Pages/Tokens/Opacity/OpacityTokenPage.swift
#157 
- (NA)  I have added unit tests to cover my changes _(optional)_
- (NA) My change introduces changes to the documentation and/or I have updated the documentation accordingly
> [#157] On opacity screen, add a border around the view showing the opacity

- CHANGELOG.md
- OUDS/Core/OUDS/Sources/OUDSTheme/OUDSTheme+SemanticTokens/OUDSTheme+ColorSemanticTokens.swift
- OUDS/Core/OUDS/Tests/OUDSTheme/MockTheme/MockTheme+ColorSemanticTokens.swift
- OUDS/Core/OUDS/Tests/OUDSTheme/TestThemeOverrideOfColorSemanticTokens.swift
- OUDS/Core/Tokens/SemanticTokens/Sources/Values/ColorSemanticTokens.swift
> [#177] Add color semantic tolens (update of October, 8th) 

- CHANGELOG.md
- OUDS/Core/OUDS/Sources/OUDSTheme/OUDSTheme+SemanticTokens/OUDSTheme+TypographySemanticTokens.swift
#191 
`typeBodyDefaultLarge` needs to be fixed
`typeBodyDefaultLarge`does not use the suitable tokens, its font weight is not the expected one
> [#191] Composite semantic token `typeBodyDefaultLarge` font weight update

- CHANGELOG.md
- Showcase/Showcase/Pages/ThemeSelection/ThemeSelection.swift
- Showcase/Showcase/Resources/en.lproj/Localizable.strings
> [#212] Fix missing accessibility labels for images in demo app

- CHANGELOG.md
- OUDS/Core/OUDS/Sources/OUDSUserInterfaceSizeClass.swift
- OUDS/Core/OUDS/Sources/_OUDS.docc/Components.md
- OUDS/Core/Tokens/ComponentTokens/Sources/_OUDSTokensComponent.docc/OUDSTokensComponent.md
- OUDS/Core/Tokens/SemanticTokens/Sources/Multiples/MultipleColorTokens.swift
- OUDS/Core/Tokens/SemanticTokens/Sources/Multiples/MultipleElevationTokens.swift
- OUDS/Foundations/Sources/Extensions/String+SwiftUI.swift
#293 
Just to fix some warnings in the documentation
Remove warnings and have better documentation 
> [#293] Remove some warnings while documentation generation

- .github/workflows/build-and-test.yml
- CHANGELOG.md
> [Tool] Use specific macOS runner version for GitHub Actions workflow

- CHANGELOG.md
- Showcase/Showcase/Pages/Tokens/Dimension/Size/SizeTokenPage.swift
- Showcase/Showcase/Pages/Tokens/Typography/TypographyTokenPage.swift
- Showcase/Showcase/Pages/Utils/ShowcaseTokenIllustration.swift
- Showcase/Showcase/Resources/accessibilityStatement/accessibility_detail.html
- Showcase/Showcase/Resources/accessibilityStatement/accessibility_result.xml
> [#285] Fix VoiceOver issue with element grouping in presentation tokens for demo app

- CHANGELOG.md
- Showcase/Podfile.lock
- Showcase/Showcase/Pages/Components/Utils/ComponentPage.swift
- Showcase/Showcase/Pages/Tokens/Border/BorderTokenPage.swift
- Showcase/Showcase/Pages/Tokens/Color/ColorTokenPage.swift
- Showcase/Showcase/Pages/Tokens/Dimension/Size/SizeTokenPage.swift
- Showcase/Showcase/Pages/Tokens/Dimension/Space/SpaceTokenPage.swift
- Showcase/Showcase/Pages/Tokens/Elevation/ElevationTokenPage.swift
- Showcase/Showcase/Pages/Tokens/Font/FontTokenPage.swift
- Showcase/Showcase/Pages/Tokens/Grid/GrisTokenPage.swift
- Showcase/Showcase/Pages/Tokens/Opacity/OpacityTokenPage.swift
- Showcase/Showcase/Pages/Utils/ShowcaseCode.swift
- Showcase/Showcase/Resources/en.lproj/Localizable.strings
> [#361] Update show code text

- CHANGELOG.md
- DesignToolbox/DesignToolbox.xcodeproj/project.pbxproj
- DesignToolbox/DesignToolbox/Pages/Components/Button/ButtonConfiguration.swift
- DesignToolbox/DesignToolbox/Pages/Components/Button/ButtonPage.swift
- DesignToolbox/DesignToolbox/Pages/Components/Link/LinkConfiguration.swift
- DesignToolbox/DesignToolbox/Pages/Components/Link/LinkPage.swift
- DesignToolbox/DesignToolbox/Pages/Utils/DesignToolboxTextField.swift
- DesignToolbox/DesignToolbox/Resources/en.lproj/Localizable.strings
- (NA) My change introduces changes to the documentation and/or I have updated the documentation accordingly
> [DesignToolbox] Add Text field in component configuration to customize text

- CHANGELOG.md
- OUDS/Core/Components/Sources/Buttons/Internal/ButtonStyle+NormalModifier.swift
> [#472] Fix border modifier on button and update changelog

- CHANGELOG.md
- DesignToolbox/DesignToolbox/Pages/Components/Checkbox/Checkbox/CheckboxElement.swift
- DesignToolbox/DesignToolbox/Pages/Components/Checkbox/Checkbox/CheckboxIndeterminateElement.swift
- DesignToolbox/DesignToolbox/Pages/Components/Checkbox/CheckboxElements.swift
- DesignToolbox/DesignToolbox/Pages/Components/Checkbox/CheckboxItem/CheckboxItemElement.swift
- DesignToolbox/DesignToolbox/Pages/Components/Checkbox/CheckboxItem/CheckboxItemIndeterminateElement.swift
- DesignToolbox/DesignToolbox/Pages/Components/Radio/Radio/RadioElement.swift
- DesignToolbox/DesignToolbox/Pages/Components/Radio/RadioElements.swift
- DesignToolbox/DesignToolbox/Pages/Components/Radio/RadioItem/RaioItemElement.swift
> [#519]  Update Checkbox and Radio button assets on the screen of components list 

- CHANGELOG.md
- DesignToolbox/DesignToolbox/Pages/Utils/Elements/DesignToolboxVariantElement.swift
#553 
If RTL mode mirrores the chevron of navigation link for Design System Toolbox
Support RTL layout
- (NA)  My change follows accessibility good practices
- (NA) Q/A eam has tested the evolution
> [#553] Fix direction of navigation link chevron in RTL mode for Design Toolbox (#553)

- CHANGELOG.md
- DesignToolbox/DesignToolbox/Pages/Utils/DesignToolboxCode.swift
#554 
For source code sample text alignment tothe left as written in english
Support RTL
> [#554] Fix code sample alignment for RTL mode in Design Toolbox

- CHANGELOG.md
- OUDS/Core/Components/Sources/Link/OUDSLink.swift
#557 
Mirrors the chevron of link component if RTL layout
Support RTL layout
- (NA) ccessibility review has been done
> [#557] Fix direction of link chevron in RTL mode for link component

- CHANGELOG.md
- DesignToolbox/DesignToolbox.xcworkspace/xcshareddata/swiftpm/Package.resolved
- DesignToolbox/DesignToolbox/Pages/Components/Button/ButtonPage.swift
- DesignToolbox/DesignToolboxSnapshotsTests/__Snapshots__/Components/OUDSButtonUITests.swift
- OUDS/Core/Components/Sources/Buttons/OUDSButton.swift
- OUDS/Core/Components/Sources/Resources/Localizable.xcstrings
#460
- [] Documentation has been updated if relevant
> [#460] Add accessibility label to vocalize the IconOnly style of button component

- CHANGELOG.md
- OUDS/Core/Components/Sources/Buttons/OUDSButton.swift
- OUDS/Core/Components/Sources/ColoredSurface/OUDSColoredSurface.swift
- OUDS/Core/Components/Sources/_OUDSComponents.docc/Actions.md
#609 
Init of `OUDSButton` has been simplified wirh default hiarchy and style
Keep API simple
> [#609] Refactor init of `OUDSButton` with default hierarchy and style

- CHANGELOG.md
- DesignToolbox/DesignToolbox/Pages/Components/Button/ButtonElement.swift
- DesignToolbox/DesignToolbox/Pages/Components/Checkbox/CheckboxElements.swift
- DesignToolbox/DesignToolbox/Pages/Components/ColoredSurface/ColoredSurfaceElement.swift
- DesignToolbox/DesignToolbox/Pages/Components/ComponentsPage.swift
- DesignToolbox/DesignToolbox/Pages/Components/Link/LinkElement.swift
- DesignToolbox/DesignToolbox/Pages/Components/Radio/RadioElements.swift
- DesignToolbox/DesignToolbox/Pages/Tokens/Border/BorderTokenElement.swift
- DesignToolbox/DesignToolbox/Pages/Tokens/Color/ColorTokenElement.swift
- DesignToolbox/DesignToolbox/Pages/Tokens/Dimension/DimensionTokenElement.swift
- DesignToolbox/DesignToolbox/Pages/Tokens/Dimension/Size/SizeTokenElement.swift
- DesignToolbox/DesignToolbox/Pages/Tokens/Dimension/Space/SpaceTokenElement.swift
- DesignToolbox/DesignToolbox/Pages/Tokens/Elevation/ElevationTokenElement.swift
- DesignToolbox/DesignToolbox/Pages/Tokens/Font/FontTokenElement.swift
- DesignToolbox/DesignToolbox/Pages/Tokens/Grid/GridTokenElement.swift
- DesignToolbox/DesignToolbox/Pages/Tokens/Opacity/OpacityTokenElement.swift
- DesignToolbox/DesignToolbox/Pages/Tokens/TokensPage.swift
- DesignToolbox/DesignToolbox/Pages/Utils/Elements/DesignToolboxElementPage.swift
- DesignToolbox/DesignToolbox/Resources/Localizable.xcstrings
#585
Tokens and components should be sorted by name in the design system toolbox app.
Thus the name of each designl toolbox element is localized during the init so as to be sure the convertion will be done and use the name for sorting purposes
Let users find easily the components by names
> [#585] Sort tokens and component in design toolbox by name

- CHANGELOG.md
- DesignToolbox/DesignToolbox/Pages/Components/Checkbox/CheckboxItem/CheckboxItemConfiguration.swift
- DesignToolbox/DesignToolbox/Pages/Components/Checkbox/CheckboxItem/CheckboxItemIndeterminateConfiguration.swift
- DesignToolbox/DesignToolbox/Pages/Components/Checkbox/CheckboxItem/CheckboxItemIndeterminatePage.swift
- DesignToolbox/DesignToolbox/Pages/Components/Checkbox/CheckboxItem/CheckboxItemPage.swift
- DesignToolbox/DesignToolbox/Pages/Components/Radio/RadioItem/RadioItemPage.swift
- DesignToolbox/DesignToolbox/Pages/Components/Radio/RadioItem/RadiolItemConfiguration.swift
- DesignToolbox/DesignToolbox/Resources/Localizable.xcstrings
- OUDS/Core/Components/Sources/Checkbox/OUDSCheckboxItem.swift
- OUDS/Core/Components/Sources/Checkbox/OUDSCheckboxItemIndeterminate.swift
- OUDS/Core/Components/Sources/Internal/ControlItem/ControlItem.swift
- OUDS/Core/Components/Sources/Internal/ControlItem/ControlItemContent.swift
- OUDS/Core/Components/Sources/Internal/ControlItem/ControlItemIconContainer.swift
- OUDS/Core/Components/Sources/Internal/ControlItem/ControlItemLabel.swift
- OUDS/Core/Components/Sources/Radio/OUDSRadio.swift
- OUDS/Core/Components/Sources/Radio/OUDSRadioItem.swift
- OUDS/Core/Components/Sources/ViewModifiers/LayoutModifiers/FlipperModifier.swift
- OUDS/Core/Components/Sources/ViewModifiers/LayoutModifiers/View+Flipper.swift
#556 
Make control-item-based component able to flip their icon content
If a radio item, a checkbox item our a switch item is used in RTL mode or with indicator in LTR trailing position, the image may be flipped. Indeed for some layouts the image direction brings meanings ; and if the image is not in the same place, the meaning can be lost. It could be interesting to let users define a boolean (default set to false) if the image must be flipped ; it is more suer friendly compared to let users flip the image themselves.
- (NA) My change respects the design guidelines of _Orange …
> [#556] Make control-item-based components able to flip images or not

- DesignToolbox/DesignToolbox/Resources/Localizable.xcstrings
#622
- (NA) I have read the [contributing guidelines](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/CONTRIBUTING.md)
- (NA) CHANGELOG has been updated respecting [keep a changelog rules](https://keepachangelog.com/en/1.0.0/) and reference the issues
> [#622] fix: update wroding for arabic

- CHANGELOG.md
- DesignToolbox/DesignToolbox/Pages/Components/Checkbox/Checkbox/CheckboxElement.swift
- DesignToolbox/DesignToolbox/Pages/Components/Checkbox/Checkbox/CheckboxIndeterminateElement.swift
- DesignToolbox/DesignToolbox/Pages/Components/Checkbox/CheckboxItem/CheckboxItemIndeterminateElement.swift
- DesignToolbox/DesignToolbox/Pages/Components/CheckboxPicker/CheckboxPickerConfiguration.swift
- DesignToolbox/DesignToolbox/Pages/Components/ColoredSurface/ColoredSurfaceElement.swift
- DesignToolbox/DesignToolbox/Resources/Localizable.xcstrings
#654
- (NA) My change introduces changes to the documentation and/or I have updated the documentation accordingly
> [#654] Udpate wordings to avoid traduction for components and tokens names

- CHANGELOG.md
- OUDS/Core/Components/Sources/Checkbox/Internal/CheckboxIndicator.swift
- OUDS/Core/Components/Sources/Checkbox/Internal/CheckboxIndicatorModifiers.swift
- OUDS/Core/Components/Sources/Checkbox/OUDSCheckbox.swift
- OUDS/Core/Components/Sources/Checkbox/OUDSCheckboxIndeterminate.swift
- OUDS/Core/Components/Sources/Internal/ControlItem/ControlItemBordersModifier.swift
- OUDS/Core/Components/Sources/Internal/InteractionState/InteractionButton.swift
- OUDS/Core/Components/Sources/Radio/Internal/RadioIndicatorModifiers.swift
Closes #645 
For radio button and checkbox components, if high contrast mode is enabled and device in light mode, change some colors for better contrast ratio without impacting hover, pressed, or error states.
But compliant with a11y rules
- (NA)  Accessibility review has been done
> [#645] Fix colors for radio and checkbox components in high contrast light mode

- CHANGELOG.md
- OUDS/Core/Components/Sources/Buttons/Internal/ButtonStyle+BorderModifier.swift
- OUDS/Core/Components/Sources/Buttons/Internal/ButtonStyle+LoadingModifiers.swift
#437 
In default loading button change color if high contrast light mode
> [#437] Fix color of default loading button in high contrast light mode

- CHANGELOG.md
- OUDS/Core/Components/Sources/Checkbox/Internal/CheckboxBackgroundColorModifier.swift
- OUDS/Core/Components/Sources/Checkbox/OUDSCheckbox.swift
- OUDS/Core/Components/Sources/Checkbox/OUDSCheckboxIndeterminate.swift
- OUDS/Core/Components/Sources/Radio/Internal/RadioBackgroundModifier.swift
- OUDS/Core/Components/Sources/Radio/OUDSRadio.swift
#720 
- (NA)  My change introduces changes to the documentation and/or I have updated the documentation accordingly
> [#720] Update background color in pressecd and hover states for Radio button and Checkbox components

- CHANGELOG.md
- OUDS/Core/Components/Sources/Checkbox/OUDSCheckboxItem.swift
- OUDS/Core/Components/Sources/Internal/ControlItem/ControlItemBordersModifier.swift
- OUDS/Core/Components/Sources/Internal/ControlItem/ControlItemContent.swift
- OUDS/Core/Components/Sources/Radio/OUDSRadioItem.swift
- OUDS/Core/Components/Sources/Switch/OUDSSwitchItem.swift
Orange-OpenSource/ouds-ios#777
> [#777] Update `controlItem` component to use `controlItemBorderRadius*` tokens

- CHANGELOG.md
- OUDS/Core/Components/Sources/Chips/Pickers/OUDSChipPicker.swift
#841 
Update the title of the ChipPicker to confor figma.
> [#841] Update typography in title of the ChipPicker component

- CHANGELOG.md
- OUDS/Core/Components/Sources/Indicators/Badge/Internal/BadgeCount.swift
- OUDS/Core/Components/Sources/Indicators/Badge/Internal/BadgeIcon.swift
- OUDS/Core/Components/Sources/Indicators/Badge/OUDSBadge.swift
- OUDS/Core/Components/Tests/Controls/Checkbox/OUDSCheckboxStateTests.swift
- OUDS/Core/Components/Tests/Indicators/Badge/OUDSBadgeIllustrationSizeTests.swift
Orange-OpenSource/ouds-ios#855
- Breaking change (fix or feature that would change existing functionality)
> [#855] Update API to use a specific size for count and icon badge types

- CHANGELOG.md
- OUDS/Core/Components/Sources/Actions/Button/Internal/ButtonStyle+BackgroundModifier.swift
- OUDS/Core/Components/Sources/Actions/Button/Internal/ButtonStyle+BorderModifier.swift
- OUDS/Core/Components/Sources/Actions/Button/Internal/ButtonStyle+ForegroundModifier.swift
- OUDS/Core/Components/Sources/Actions/Button/Internal/ButtonStyle+LoadingModifiers.swift
- OUDS/Core/Components/Sources/Actions/Button/Internal/ButtonStyle+NormalModifier.swift
- OUDS/Core/Components/Sources/Actions/Button/Internal/ButtonStyle.swift
- OUDS/Core/Components/Sources/Actions/Button/OUDSButton.swift
- OUDS/Core/Components/Sources/Layouts/ColoredSurface/OUDSColoredSurface.swift
- OUDS/Core/Components/Sources/_OUDSComponents.docc/Actions.md
#969 
Rename the _hierarchy_ property of the _button_ component to _appearance_.
Anticipate enxt Figma evolutions.
> [#969] `hierarchy` button component property renamed to `appearance`

- CHANGELOG.md
- OUDS/Core/Components/Sources/_OUDSComponents.docc/_OUDSComponents.md
- OUDS/Core/Themes/Orange/Sources/OrangeTheme.swift
- OUDS/Core/Themes/OrangeBusinessTools/Sources/OrangeBusinessToolsTheme.swift
- OUDS/Core/Themes/OrangeInverse/Sources/OrangeInverseTheme.swift
- OUDS/Foundations/Sources/PostScriptFontNamesMap.swift
- OUDS/Foundations/Tests/PostScriptFontNamesMapTests.swift
#1006 
- Update PostScript map to be able to manage _Helvetica Neue Arabic_ font family and its weights
- Update documentation to explain to users how to use it and provide code samples for fonts registering and use of font family depending to language
Provide _Helvetica Neue_ variant for arabic apps
> [#1006] Manage `Helvetica Neue Arabic` font family
